projects:
  zenbuildup:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: graphql
        maxDepth: 7
extensions:
  amplify:
    version: 3
